In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 


In [2]:
tf.__version__

'2.19.0'

In [3]:
dataset  = pd.read_csv(r"E:\Datasets\Churn_Modelling.csv")

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [26]:
X

array([[ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.        ,  0.        , -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 1.        ,  0.        ,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 0.        ,  1.        , -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.        ,  0.        ,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 13))

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [29]:
X

array([[ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 0.57873591, -0.57873591, -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.57873591, -0.57873591,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.72790383,  1.72790383, -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 13))

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [32]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 5,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 4,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [33]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])


In [34]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 150,validation_data = (X_test,y_test))

Epoch 1/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7549 - loss: 0.5747 - val_accuracy: 0.7975 - val_loss: 0.4867
Epoch 2/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7960 - loss: 0.4642 - val_accuracy: 0.7975 - val_loss: 0.4536
Epoch 3/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7960 - loss: 0.4439 - val_accuracy: 0.7975 - val_loss: 0.4375
Epoch 4/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7970 - loss: 0.4314 - val_accuracy: 0.8110 - val_loss: 0.4252
Epoch 5/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4232 - val_accuracy: 0.8270 - val_loss: 0.4143
Epoch 6/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8226 - loss: 0.4149 - val_accuracy: 0.8300 - val_loss: 0.4064
Epoch 7/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8271 - loss: 0.4068 - val_accuracy: 0.8295 - val_loss: 0.3992
Epoch 8/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8341 - loss: 0.3980 - val_accu

In [35]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [36]:
y_pred = y_pred > 0.5

In [37]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis = 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac = accuracy_score(y_test,y_pred)
ac

0.865

In [39]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1531,   64],
       [ 206,  199]])